/// <reference types="nativewind/types" />
// Adds the `className` prop to React Native components' TypeScript types.

/// <reference types="expo/types" />
// Lets `import '@/global.css'` typecheck. expo-env.d.ts has the same line, but
// it's generated by `expo start` and gitignored, so CI never sees it.
